- name: installing nginx
  hosts: web
  become: yes

  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: installed
      
    - name: start and enable the nginx
      ansible.builtin.service:
        name: nginx
        enabled: yes
        state: started
          
