- name: variables
  hosts: local
  connection: local
  vars:
    PROJECT: QBE
    ENVIRONMENT: DEV

  tasks:
    - name: print the variables
      ansible.builtin.debug:
        msg: "Project is {{ PROJECT }} Environment is {{ ENVIRONMENT }}"