- name: variables
  hosts: local
  connection: local
  vars:
    PROJECT: SABRE
    ENVIRONMENT: TEST

  tasks:
    - name: printing the variables
      vars:
        PROJECT: EXE
        ENVIRONMENT: QA
      ansible.builtin.debug:
        msg: "Project is {{ PROJECT }} Environment is {{ ENVIRONMENT }}"  

    - name: print the play variables
      ansible.builtin.debug:
        msg: "Project is {{ PROJECT }} Environment is {{ ENVIRONMENT }}"    