- name: variables
  hosts: local
  connection: local
  var_files:
    - project.yaml
  tasks:
    - name: print the variables
      ansible.builtin.debug:
        msg: "Project is {{ PROJECT }} Environment is {{ ENVIRONMENT }}"  